base-chart:
  namespace: int
  serviceName: tmdb-app

  ingress:
    ingressClassName: nginx
    name: tmdb-ing
    namespace: int
    annotations: 
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    rules:
    - host: tmdb.ma-devops.com
      paths:
        - path: /
          service: tmdb-svc
          port: 3000

  deployment:
    image: us-central1-docker.pkg.dev/hamzahllc-technical-task/tmdb-tasks/tmdb-app
    tag: latest
    replicaCount: 1
    restartPolicy: Always
    serviceAccountName: {}
    resources:
      requests:
        cpu: 30m
        memory: 10Mi
      limits:
        # cpu: 800m
        memory: 800Mi
    livenessProbe:
      httpGet:
        path: /
        port: 3000
      initialDelaySeconds: 60
    ports:
    - name: app-port
      containerPort: 3000

  service:
    name: tmdb-svc
    labels: {}
    selector:
      app: tmdb-app 
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 3000
      targetPort: app-port

