base-chart:
  name: tmdb-app
  namespace: int

  ingress:
    ingressClassName: nginx
    name: tmdb-ing
    namespace: int
    annotations: 
      kubernetes.io/ingress.class: "nginx"
      nginx.ingress.kubernetes.io/ssl-redirect: "false"
    rules:
    - host: tmdb.ma-devops.com
      paths:
        - path: /
          service: tmdb-svc
          port: 3000

  deployment:
    annotations: {}
    image: us-central1-docker.pkg.dev/hamzahllc-technical-task/tmdb-tasks/tmdb-app
    tag: latest
    restartPolicy: Always
    serviceAccountName: {}
    resources:
      requests:
        cpu: 30m
        memory: 10Mi
      limits:
        cpu: 200m
        memory: 800Mi
    ports:
    - name: app-port
      containerPort: 3000

  service:
    name: tmdb-svc
    labels: {}
    selector:
      app: tmdb-app 
    type: ClusterIP
    ports:
    - protocol: TCP
      port: 3000
      targetPort: app-port

