apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tmdb-application
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true 
      selfHeal: true 
      allowEmpty: false 
  sources:
  - repoURL: 'https://github.com/mohamedalaaelsafy/tmdb-task3.git'
    targetRevision: HEAD
    path: helm/app-charts/tmdb
    helm:
      releaseName: tmdb-app
      valueFiles:
      - int.yaml
