image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_IMAGE_NAME: "tmdb"  # Replace with your desired Docker image name
  TAG: "latest"

stages:
  - build
  - lint
  - test
  - push

before_script:
  - apk update && apk add nodejs npm
  - docker login -u $CI_REGISTRY_USER -p $CI_JOB_TOKEN $CI_REGISTRY

build:
  stage: build
  script:
    - echo "Building the application..."
    - npm install
    - npm run build
  artifacts:
    paths:
      - node_modules/
  only:
    - main

lint:
  stage: lint
  dependencies:
    - build
  script:
    - echo "Linting the code..."
    - npm run lint
  only:
    - main

test:
  stage: test
  dependencies:
    - build
  script:
    - echo "Running tests..."
    - npm run test || true
  only:
    - main

push:
  stage: push
  script:
    - echo "Deploying to GitLab Container Registry..."
    - docker build -t $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME:$TAG .
    - docker push $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME:$TAG
  only:
    - main
  environment:
    name: production
    url: $CI_REGISTRY_IMAGE/$DOCKER_IMAGE_NAME:$TAG
